/**
 * Domain types for the Smart Campaigns experience on the Marketing tab.
 *
 * Two creation modes share the same Campaign entity:
 *   - "manual"  → user walked through the 4-step wizard from scratch
 *   - "agentic" → Spyne suggested the campaign (from aging / holding-cost
 *     signals) or the user described it via the prompt input. The wizard
 *     opens directly on Step 04 with the suggestion pre-filled.
 */

export type CampaignKind = "manual" | "agentic"

/** Live status of a campaign as it travels through publish + run. */
export type CampaignStatus =
  | "draft"
  | "scheduled"
  | "running"
  | "paused"
  | "completed"

/** Promotion channels available across the wizard's Design + Schedule steps. */
export type CampaignChannel =
  | "google-ads"
  | "meta-ads"
  | "autotrader"
  | "cars-dot-com"
  | "email"
  | "sms"
  | "vlp-spotlight"
  | "social-organic"

/**
 * Why Spyne is suggesting a campaign. Drives the row's icon + tone +
 * trigger sentence on the suggestion card.
 */
export type CampaignTrigger =
  | "aged-30"
  | "aged-45"
  | "aged-60"
  | "high-holding-cost"
  | "price-cut"
  | "hot-demand"
  | "festive"
  | "certified-pre-owned"

/** Grouping for the three Suggested-for-you sections on the landing. */
export type CampaignSuggestionCategory = "festive" | "aging" | "certified"

/** Aging bucket — used for grouping/sorting suggestions. */
export type AgingBucket = "30d" | "45d" | "60d"

/** Subset of vehicle data used inside the campaign experience. */
export interface CampaignVehicle {
  vin: string
  name: string
  year: number
  make: string
  model: string
  trim?: string
  /** Days the VIN has been in stock (drives aging buckets). */
  daysInStock: number
  /** Holding cost accumulated to date in USD. */
  holdingAccumulated: number
  /** Listing price in USD. */
  price: number
  /** Thumbnail URL. */
  thumbnailUrl: string
}

/** Inferred budget + channel mix Spyne would launch if the user accepts as-is. */
export interface CampaignAutoConfig {
  channels: CampaignChannel[]
  /** Total budget the agent would set for the campaign window. */
  budget: number
  /** Run window in days. */
  durationDays: number
  /** ISO timestamp the suggested send is scheduled for. */
  scheduledFor: string
  /** Headline + body Spyne would use for ad creative + email subject. */
  creative: {
    headline: string
    body: string
  }
}

/** Expected results if launched as-suggested. Drives the impact tiles. */
export interface CampaignProjection {
  impressions: number
  leads: number
  appointments: number
  unitsSold: number
  estimatedSpend: number
  /** Holding-cost saved per VIN sold sooner. */
  estimatedHoldingSavings: number
}

/**
 * A single agentic suggestion. Generated by aggregating VINs that fall into
 * a trigger bucket (aged 45+, high holding cost, etc.) and pre-computing
 * a campaign config + projection.
 */
export interface CampaignSuggestion {
  id: string
  trigger: CampaignTrigger
  category: CampaignSuggestionCategory
  bucket?: AgingBucket
  /** Short headline shown on the suggestion card ("Move your 45+ day aged inventory"). */
  title: string
  /** One-sentence trigger story ("12 VINs aged > 45d — $48k in holding cost piling up"). */
  reason: string
  /** VINs targeted by this campaign. */
  vehicles: CampaignVehicle[]
  /** Pre-filled wizard config. */
  config: CampaignAutoConfig
  /** Projected outcome. */
  projection: CampaignProjection
  /** When the suggestion was surfaced. */
  surfacedAt: string
}

/** Live performance snapshot for a created campaign. */
export interface CampaignPerformance {
  impressions: number
  leads: number
  appointments: number
  unitsSold: number
  spend: number
}

/** Fully created campaign — listed under "My campaigns" on the landing. */
export interface Campaign {
  id: string
  kind: CampaignKind
  status: CampaignStatus
  title: string
  /** Resolved from the trigger when kind === "agentic". */
  trigger?: CampaignTrigger
  vehicles: CampaignVehicle[]
  config: CampaignAutoConfig
  /** Performance counters; zeros for non-running campaigns. */
  performance: CampaignPerformance
  /** ISO timestamps. */
  createdAt: string
  launchedAt?: string
  endsAt?: string
}

/* ────────────────────────── Wizard model ────────────────────────── */

/** Steps of the manual wizard. Agentic flows jump directly to "review". */
export type CampaignWizardStep = "inventory" | "design" | "schedule" | "review"

/**
 * Working draft inside the wizard. Either populated empty (manual entry)
 * or pre-filled from a CampaignSuggestion (agentic entry).
 */
export interface CampaignWizardDraft {
  id: string
  step: CampaignWizardStep
  /** Used to render the agentic chip + prompt echo when applicable. */
  kind: CampaignKind
  /** Free-text prompt the user typed (agentic flow only). */
  prompt?: string
  /** Source suggestion if launched from a suggestion card. */
  sourceSuggestionId?: string
  title: string
  vehicles: CampaignVehicle[]
  config: CampaignAutoConfig
  projection: CampaignProjection
}
